# Generated by Django 5.0.6 on 2025-01-17 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=12)),
                ('endereco', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('data_nasc', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_entrada', models.DateField()),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Manutencao', 'Manutenção'), ('Alta', 'Alta'), ('Obito', 'Óbito'), ('Paleativo', 'Paleativo')], max_length=20)),
                ('tipo_cancer', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cereais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cesta', models.CharField(blank=True, choices=[('basica', 'Básica'), ('frutas', 'Frutas'), ('legumes', 'Legumes'), ('cereais', 'Cereais')], max_length=20, null=True)),
                ('opcao_cesta', models.CharField(blank=True, choices=[('cesta_alternada', 'Cesta Alternada'), ('mensal', 'Mensal'), ('tempo_indeterminado', 'Tempo Indeterminado'), ('suspensa', 'Suspensa')], max_length=20, null=True)),
                ('cereais', models.BooleanField(default=False)),
                ('quantidade_cereais', models.IntegerField(blank=True, default=0)),
                ('frutas', models.BooleanField(default=False)),
                ('quantidade_frutas', models.IntegerField(blank=True, default=0)),
                ('nutren', models.BooleanField(default=False)),
                ('quantidade_nutren', models.IntegerField(blank=True, default=0)),
                ('fraldas', models.BooleanField(default=False)),
                ('quantidade_fraldas', models.IntegerField(blank=True, default=0)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
